version: v1

labels:
  - label: 'Enhancement'
    sync: true
    matcher:
      commits: '^feat.*?:'
      title: '^feat.*?:'

  - label: 'Bug'
    sync: true
    matcher:
      commits: '^fix.*?:'
      title: '^fix.*?:'

  - label: 'Documentation'
    sync: true
    matcher:
      commits: '^docs.*?:'
      title: '^docs.*?:'
      files: ['packages/docutils/**', 'packages/appium/docs/**', '**/*.md']

  - label: 'chore'
    sync: true
    matcher:
      commits: '^chore.*?:'
      title: '^chore.*?:'
      files: ['.github/**', '.husky/**', '.vscode/**', './.*', './*.js', '**/test/**']

  - label: 'SemVer:Breaking'
    sync: true
    matcher:
      commits: '(^(.+?)!:)|(BREAKING CHANGE:)'

  - label: 'Dependencies'
    sync: true
    matcher:
      files: ['**/package.json', 'package-lock.json', '**/requirements.txt']
      author: 'renovate'

  - label: 'appium core'
    sync: true
    matcher:
      files: ['packages/appium/**']

  - label: '@testspectra/base-driver'
    sync: true
    matcher:
      files: ['packages/base-driver/**']

  - label: '@testspectra/base-plugin'
    sync: true
    matcher:
      files: ['packages/base-plugin/**']

  - label: '@testspectra/storage-plugin'
    sync: true
    matcher:
      files: ['packages/storage-plugin/**']

  - label: '@testspectra/docutils'
    sync: true
    matcher:
      files: ['packages/docutils/**']

  - label: '@testspectra/driver-test-support'
    sync: true
    matcher:
      files: ['packages/driver-test-support/**']

  - label: '@testspectra/eslint-config-appium-ts'
    sync: true
    matcher:
      files: ['packages/eslint-config-appium-ts/**']

  - label: '@testspectra/execute-driver-plugin'
    sync: true
    matcher:
      files: ['packages/execute-driver-plugin/**']

  - label: '@testspectra/fake-driver'
    sync: true
    matcher:
      files: ['packages/fake-driver/**']

  - label: '@testspectra/fake-plugin'
    sync: true
    matcher:
      files: ['packages/fake-plugin/**']

  - label: '@testspectra/images-plugin'
    sync: true
    matcher:
      files: ['packages/images-plugin/**']

  - label: '@testspectra/logger'
    sync: true
    matcher:
      files: ['packages/logger/**']

  - label: '@testspectra/opencv'
    sync: true
    matcher:
      files: ['packages/opencv/**']

  - label: '@testspectra/plugin-test-support'
    sync: true
    matcher:
      files: ['packages/plugin-test-support/**']

  - label: '@testspectra/relaxed-caps-plugin'
    sync: true
    matcher:
      files: ['packages/relaxed-caps-plugin/**']

  - label: '@testspectra/schema'
    sync: true
    matcher:
      files: ['packages/schema/**']

  - label: '@testspectra/support'
    sync: true
    matcher:
      files: ['packages/support/**']

  - label: '@testspectra/strongbox'
    sync: true
    matcher:
      files: ['packages/strongbox/**']

  - label: '@testspectra/test-support'
    sync: true
    matcher:
      files: ['packages/test-support/**']

  - label: '@testspectra/tsconfig'
    sync: true
    matcher:
      files: ['packages/tsconfig/**']

  - label: '@testspectra/types'
    sync: true
    matcher:
      files: ['packages/types/**']

  - label: '@testspectra/universal-xml-plugin'
    sync: true
    matcher:
      files: ['packages/universal-xml-plugin/**']
